export const CATEGORIES = ["All", "Circuits", "Chemistry", "Workflows"];

export const TEMPLATES = [
  // ── Genetic Circuits ─────────────────────────────────────────────────────
  {
    id: "inducible-gfp",
    category: "Circuits",
    title: "Inducible GFP",
    desc: "IPTG-inducible GFP reporter — the canonical single-gene expression circuit",
    icon: "🧬",
    accent: "var(--ft-circuit)",
    type: "circuit",
    content: "Express GFP when IPTG is present",
  },
  {
    id: "toggle-switch",
    category: "Circuits",
    title: "Toggle Switch",
    desc: "Bistable memory element toggled by IPTG and aTc (Gardner et al. 2000)",
    icon: "🔀",
    accent: "var(--ft-circuit)",
    type: "circuit",
    content: "Bistable toggle switch: LacI represses TetR, TetR represses LacI; IPTG flips state up, aTc flips state down",
  },
  {
    id: "repressilator",
    category: "Circuits",
    title: "Repressilator",
    desc: "Three-gene transcriptional oscillator with GFP reporter (Elowitz & Leibler 2000)",
    icon: "🔄",
    accent: "var(--ft-circuit)",
    type: "circuit",
    content: "Repressilator oscillator: LacI represses TetR, TetR represses CI, CI represses LacI; add GFP reporter on LacI promoter",
  },
  {
    id: "band-pass",
    category: "Circuits",
    title: "Band-pass Filter",
    desc: "Expresses GFP only at intermediate arabinose levels via activator-repressor cascade",
    icon: "🎚️",
    accent: "var(--ft-circuit)",
    type: "circuit",
    content: "Band-pass filter: express GFP only at intermediate arabinose concentrations using an activator-repressor cascade",
  },
  {
    id: "and-gate",
    category: "Circuits",
    title: "AND Gate",
    desc: "Boolean AND — RFP fires only when both IPTG and aTc are present simultaneously",
    icon: "⊓",
    accent: "var(--ft-circuit)",
    type: "circuit",
    content: "AND gate: express RFP only when both IPTG and aTc are present simultaneously",
  },
  {
    id: "feed-forward",
    category: "Circuits",
    title: "Feed-forward Loop",
    desc: "Coherent type-1 FFL — delays GFP off-response when arabinose is removed",
    icon: "↗️",
    accent: "var(--ft-circuit)",
    type: "circuit",
    content: "Coherent type-1 feed-forward loop: arabinose activates both AraC and GFP; AraC also activates GFP; results in delayed off-response",
  },
  {
    id: "quorum-sensor",
    category: "Circuits",
    title: "Quorum Sensor",
    desc: "AHL-responsive population density detector with GFP output",
    icon: "👥",
    accent: "var(--ft-circuit)",
    type: "circuit",
    content: "Quorum sensing circuit: express GFP in response to AHL above a threshold, modeling cell-density-dependent activation",
  },
  {
    id: "bifan-motif",
    category: "Circuits",
    title: "Bi-fan Motif",
    desc: "Two inputs (IPTG, aTc) co-regulate two outputs (GFP, RFP) through cross-connections",
    icon: "🕸️",
    accent: "var(--ft-circuit)",
    type: "circuit",
    content: "Bi-fan motif: IPTG and aTc each activate both GFP and RFP with different kinetics, creating a multi-output integration circuit",
  },

  // ── Chemistry ────────────────────────────────────────────────────────────
  {
    id: "aspirin",
    category: "Chemistry",
    title: "Aspirin",
    desc: "Acetylsalicylic acid — analgesic, anti-inflammatory; Lipinski rule-of-5 compliant",
    icon: "💊",
    accent: "var(--ft-chemistry)",
    type: "molecule",
    content: "CC(=O)Oc1ccccc1C(=O)O",
    meta: { smiles: "CC(=O)Oc1ccccc1C(=O)O", name: "Aspirin" },
  },
  {
    id: "caffeine",
    category: "Chemistry",
    title: "Caffeine",
    desc: "1,3,7-trimethylxanthine — adenosine receptor antagonist; CNS stimulant",
    icon: "☕",
    accent: "var(--ft-chemistry)",
    type: "molecule",
    content: "Cn1cnc2c1c(=O)n(C)c(=O)n2C",
    meta: { smiles: "Cn1cnc2c1c(=O)n(C)c(=O)n2C", name: "Caffeine" },
  },
  {
    id: "atp",
    category: "Chemistry",
    title: "ATP",
    desc: "Adenosine triphosphate — universal cellular energy currency; phosphoryl donor",
    icon: "⚡",
    accent: "var(--ft-chemistry)",
    type: "molecule",
    content: "c1nc(N)c2ncnc2n1[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O)OP(=O)(O)O)[C@@H](O)[C@H]1O",
    meta: {
      smiles: "c1nc(N)c2ncnc2n1[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O)OP(=O)(O)O)[C@@H](O)[C@H]1O",
      name: "ATP",
    },
  },
  {
    id: "glucose-oxidation",
    category: "Chemistry",
    title: "Glucose Oxidation",
    desc: "Balanced combustion C₆H₁₂O₆ + 6 O₂ → 6 CO₂ + 6 H₂O with ODE kinetics",
    icon: "🔥",
    accent: "var(--ft-chemistry)",
    type: "reaction",
    content: "C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O)O)O)O)O.O=O>>O=C=O.O",
    meta: {
      reactionSmiles: "C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O)O)O)O)O.O=O>>O=C=O.O",
      name: "Glucose Oxidation",
    },
  },
  {
    id: "acid-base",
    category: "Chemistry",
    title: "Acid-Base Titration",
    desc: "HCl + NaOH neutralisation with equivalence-point detection and pH curve",
    icon: "🧪",
    accent: "var(--ft-chemistry)",
    type: "reaction",
    content: "[H+].[Cl-].[Na+].[OH-]>>[Na+].[Cl-].O",
    meta: {
      reactionSmiles: "[H+].[Cl-].[Na+].[OH-]>>[Na+].[Cl-].O",
      name: "HCl + NaOH Neutralisation",
    },
  },

  // ── Workflows ────────────────────────────────────────────────────────────
  {
    id: "glycolysis-fba",
    category: "Workflows",
    title: "Glycolysis FBA",
    desc: "Upper glycolysis flux-balance analysis with 8 reactions and ATP yield objective",
    icon: "⚗️",
    accent: "var(--ft-pathway)",
    type: "pathway",
    content: "",
    meta: { template: "upper_glycolysis" },
  },
  {
    id: "pcr-primers",
    category: "Workflows",
    title: "PCR Primer Design",
    desc: "Design Tm-matched primer pairs using SantaLucia nearest-neighbor thermodynamics",
    icon: "🔬",
    accent: "var(--ft-sequence)",
    type: "primers",
    content: "",
    meta: {},
  },
  {
    id: "experiment-notebook",
    category: "Workflows",
    title: "Experiment Notebook",
    desc: "Structured wet-lab notebook: protocol, reagents, observations, and results table",
    icon: "📓",
    accent: "var(--ft-notebook)",
    type: "notebook",
    content: "",
    meta: {},
  },
];

const TITLE_SUFFIXES = {
  circuit: ".biopro",
  molecule: ".smiles",
  reaction: ".rxn",
  pathway: ".pathway",
  notebook: ".notebook",
  primers: "",
  alignment: "",
};

export function templateTabTitle(tpl) {
  if (tpl.type === "primers") return "Primer Design";
  return tpl.id + (TITLE_SUFFIXES[tpl.type] ?? "." + tpl.type);
}
